### ISSUE TITLE
Error with testing a new pull request

### ISSUE THREAD

**Issue by damalov** [holodeck-b2b/Holodeck-B2B#120]
I've tested one-way push message on localhost and it was ok.
I faced with problems when i set up the Pull request.
"MessageSubmission not handled by P-Mode configured handlers => check global configuration"

**Comment by sfieten** [comment]
Hi @damalov,
the log message may indeed be a bit confusing. What you're getting is from the `org.holodeckb2b.common.events.SyncEventProcessor` component and indicates that the _MessageSubmission_ **event**  is not handled. However that event actually indicates that a message was successfully submitted. So this message does not indicate an issue in the actual message exchange.
Maybe the problem is that you didn't submit a message to be pulled on the other instance? If you have further questions or need additional support, please see http://holodeck-b2b.org/support/
