### ISSUE TITLE
Missing dependency in holodeckb2b-distribution

### ISSUE THREAD

**Issue by sopgreg** [holodeck-b2b/Holodeck-B2B#122]
My build of the module `holodeckb2b-distribution` fails on master branch because of a missing dependency. Where to get this dependency from? Commenting out this dependency seems to work, though.

```
<dependency>
   <groupId>org.holodeckb2b.extensions</groupId>
   <artifactId>file-backend</artifactId>
   <version>1.0.1</version>
</dependency>
```

**Comment by RenateS** [comment]
The distribution includes the [file based back end integration](https://github.com/holodeck-b2b/file-backend) which is a separate repository under the Holodeck B2B account. If you want to build Holodeck B2B yourself instead of using the binaries, you will have to compile and install this module in your local Maven repo (unless you don't plan on using the file based back end of course).
