### ISSUE TITLE
OtherContentError (EBMS:0004) has recommended severity "failure"

### ISSUE THREAD

**Issue by tigran-a** [holodeck-b2b/Holodeck-B2B#141]
Hi, 

By the [ebms core spec](http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/core/pr02/ebms_core-3.0-spec-pr-02.html#6.7.1.ebMS%20Processing%20Errors|outline) the severity of EBMS:0004 should be "failure", while holodeckb2b uses as default "warning":
https://github.com/holodeck-b2b/Holodeck-B2B/blob/73b5caf22ad04a965ef1874c12533523a726e63b/modules/holodeckb2b-core/src/main/java/org/holodeckb2b/common/errors/OtherContentError.java#L34

Thanks

**Comment by sfieten** [comment]
The recommended severity of the _Other_ error indeed is _failure_. Because this error is used for situations where the other errors cannot be used it could also indicate a situation that could be resolved when a message is resent. This is indicated by severity level _warning_. Therefore we have decided to set the default severity for the _Other_ error to this value.
